### ISSUE TITLE
Typo in name sock_addr_aduit_key

### ISSUE THREAD

**Issue by setharnold** [Azure/GuestProxyAgent#55]
https://github.com/Azure/GuestProxyAgent/blob/c47351bff371eb73f9ea6346c70953a023fc5e98/linux-ebpf/ebpf_cgroup.c#L29C17-L29C36

Hello, there appears to be a typo in the name `sock_addr_aduit_key`, which should probably be `audit`.

I recommend installing an action like https://www.check-spelling.dev/ to help find mistakes during development rather than when you find features are missing or have never been tested, etc.

Thanks

**Comment by ZhidongPeng** [comment]
Thanks, fixed here https://github.com/Azure/GuestProxyAgent/pull/67

**Comment by balakreddy** [comment]
@ZhidongPeng I didn't notice it was assigned to you. If you are working on the github action along with the typos. I can close the pull request https://github.com/Azure/GuestProxyAgent/pull/68

**Comment by balakreddy** [comment]
@setharnold and @ZhidongPeng I added the github action for spell check as part of #68. It highlighted good number of typos
I am planning to fix all the typos. I will be sending the single PR. If it is too big, will split it and send out separate PRs.

**Comment by balakreddy** [comment]
Additional pull request #69 which fixes some of the typos based on the results from #68

**Comment by ZhidongPeng** [comment]
Resume the pull request with new one https://github.com/Azure/GuestProxyAgent/pull/136
